Repository openshift/request-header-saml-service-provider, pull requests merged in 2019-02, with the labels that each got.

#14 README.md - updates to the SSL instructions
  README.md
Labels: needs-ok-to-test, size/M

#17 Major overhaul of instructions, re-organize of folder structure, and addition of debug image
  README.md
  mellon_create_metadata.sh
  saml-auth-template.yml
  saml-auth.template
  saml-service-provider/10-auth_mellon.conf.debug
  saml-service-provider/Dockerfile
  saml-service-provider/Dockerfile.debug
  saml-service-provider/httpd.conf
  saml-service-provider/logged_out.html
  saml-service-provider/openshift.conf
  saml-service-provider/openshift.conf.debug
  saml-service-provider/run-httpd.sh
  saml-service-provider/ssl.conf
Labels: needs-ok-to-test, size/XL

#19 testing_with_keycloak.md - fix formatting issue
  keycloak/testing_with_keycloak.md
Labels: needs-ok-to-test, size/XS

#18 Documentation Cleanup / Spelling Fixes
  README.md
Labels: needs-ok-to-test, size/S

#20 README.md - various fixes
  README.md
Labels: needs-ok-to-test, size/S
